# BlockRacing 游戏设置
# 该配置文件仅用于服务器重启后保留设置数据
# 服务器关闭时将自动保存本局游戏的设置到该文件
# 如果服务器已启动，请前往游戏中的设置界面进行设置，不要在这里调整

# 语言
lang: zh_cn

# 除去 1 分目标以外的额外进度分值段设置
medium-block: true
hard-block: true

# 每局从总池子抽取的目标数量
block-amount: 64

# 同时可做/可见的队首任务数量
# 默认：64
# 最大：128
available-task-amount: 64

# 游戏模式：
# normal - 普通模式：两个队伍需要收集的方块及顺序完全随机，收集方块会将一组该方块给到对方的队伍箱子里
# racing - 竞速模式：两个队伍需要收集的方块及顺序将完全相同，且收集方块将不会给予一组方块到对方队伍箱子里
game-mode: racing

# 极速模式：
# 开启极速模式后，开局时将会给予玩家部分道具和效果
# 物品：精准采集铁镐、熟牛排、损坏的鞘翅、经验修补附魔书
# 效果：急迫V
speed-mode: false

# 团队箱子个数
# 默认：8
# 最大：53
max-team-chest-num: 8

# 路径点个数
# 默认：8
# 最大：53
max-team-waypoint-num: 8

# 如果你不知道这是什么，不要动它
config-version: 3.5
